export const homeMessages = [
    "Bespoke Web Design",
    "E-Commerce Specialists",
    "Full-Stack Web Applications",
    "Fully Dynamic Content",
    "Shoppify, Wordpress, Wix",
    "Professional Web Services",
    "Custom Domains and Emails",
    "Online Consultations",
    "UI/UX Design",
]

export const textSliderMessages = [
    "Bespoke Web Design",
    "E-Commerce",
    "Full-Stack Web Applications",
    "Apps",
    "Website Glow-ups",
    "Dynamic Content",
    "Shoppify, Wordpress, Wix, Squarespace",
    "Database Management",
    "Custom Domains and Emails",
    "Online Consultations",
    "UI/UX Design",
    "Tech Solutions",
    "React Typescript",
    "NextJS",
    "Freelance projects",
    "Travel Sites",
    "Site Plugins",
    "Frontend Development",
    "Backend Development",
    "Refresh your site",
    "Web Support",
]

export const fontStyles = [
    "font-raleway",
    "font-kumbh",
    "font-dm",
    "font-quicksand",
    "font-ubuntu",
    "font-kode",
    "font-ojuju",
]

export const toDynamicColors = [
    "to-color1",
    "to-color2",
    "to-color3",
    "to-color4",
    "to-color5",
    "to-color6",
    "to-color7",
    "to-color8",
    "to-color9",
    "to-color10",
    "to-color1-light",
    "to-color2-light",
    "to-color3-light",
    "to-color4-light",
    "to-color5-light",
    "to-color6-light",
    "to-color7-light",
    "to-color8-light",
    "to-color9-light",
    "to-color10-light",
    "to-color1-dark",
    "to-color2-dark",
    "to-color3-dark",
    "to-color4-dark",
    "to-color5-dark",
    "to-color6-dark",
    "to-color7-dark",
    "to-color8-dark",
    "to-color9-dark",
    "to-color10-dark",
]

export const fromDynamicColors = [
    "from-color1",
    "from-color2",
    "from-color3",
    "from-color4",
    "from-color5",
    "from-color6",
    "from-color7",
    "from-color8",
    "from-color9",
    "from-color10",
    "from-color1-light",
    "from-color2-light",
    "from-color3-light",
    "from-color4-light",
    "from-color5-light",
    "from-color6-light",
    "from-color7-light",
    "from-color8-light",
    "from-color9-light",
    "from-color10-light",
    "from-color1-dark",
    "from-color2-dark",
    "from-color3-dark",
    "from-color4-dark",
    "from-color5-dark",
    "from-color6-dark",
    "from-color7-dark",
    "from-color8-dark",
    "from-color9-dark",
    "from-color10-dark",
]

export const beforeToDynamicColors = [
    "before:to-color1",
    "before:to-color2",
    "before:to-color3",
    "before:to-color4",
    "before:to-color5",
    "before:to-color6",
    "before:to-color7",
    "before:to-color8",
    "before:to-color9",
    "before:to-color10",
    "before:to-color1-light",
    "before:to-color2-light",
    "before:to-color3-light",
    "before:to-color4-light",
    "before:to-color5-light",
    "before:to-color6-light",
    "before:to-color7-light",
    "before:to-color8-light",
    "before:to-color9-light",
    "before:to-color10-light",
    "before:to-color1-dark",
    "before:to-color2-dark",
    "before:to-color3-dark",
    "before:to-color4-dark",
    "before:to-color5-dark",
    "before:to-color6-dark",
    "before:to-color7-dark",
    "before:to-color8-dark",
    "before:to-color9-dark",
    "before:to-color10-dark",
]

export const beforeFromDynamicColors = [
    "before:from-color1",
    "before:from-color2",
    "before:from-color3",
    "before:from-color4",
    "before:from-color5",
    "before:from-color6",
    "before:from-color7",
    "before:from-color8",
    "before:from-color9",
    "before:from-color10",
    "before:from-color1-light",
    "before:from-color2-light",
    "before:from-color3-light",
    "before:from-color4-light",
    "before:from-color5-light",
    "before:from-color6-light",
    "before:from-color7-light",
    "before:from-color8-light",
    "before:from-color9-light",
    "before:from-color10-light",
    "before:from-color1-dark",
    "before:from-color2-dark",
    "before:from-color3-dark",
    "before:from-color4-dark",
    "before:from-color5-dark",
    "before:from-color6-dark",
    "before:from-color7-dark",
    "before:from-color8-dark",
    "before:from-color9-dark",
    "before:from-color10-dark",
]

export const afterToDynamicColors = [
    "after:to-color1",
    "after:to-color2",
    "after:to-color3",
    "after:to-color4",
    "after:to-color5",
    "after:to-color6",
    "after:to-color7",
    "after:to-color8",
    "after:to-color9",
    "after:to-color10",
    "after:to-color1-light",
    "after:to-color2-light",
    "after:to-color3-light",
    "after:to-color4-light",
    "after:to-color5-light",
    "after:to-color6-light",
    "after:to-color7-light",
    "after:to-color8-light",
    "after:to-color9-light",
    "after:to-color10-light",
    "after:to-color1-dark",
    "after:to-color2-dark",
    "after:to-color3-dark",
    "after:to-color4-dark",
    "after:to-color5-dark",
    "after:to-color6-dark",
    "after:to-color7-dark",
    "after:to-color8-dark",
    "after:to-color9-dark",
    "after:to-color10-dark",
]

export const afterFromDynamicColors = [
    "after:from-color1",
    "after:from-color2",
    "after:from-color3",
    "after:from-color4",
    "after:from-color5",
    "after:from-color6",
    "after:from-color7",
    "after:from-color8",
    "after:from-color9",
    "after:from-color10",
    "after:from-color1-light",
    "after:from-color2-light",
    "after:from-color3-light",
    "after:from-color4-light",
    "after:from-color5-light",
    "after:from-color6-light",
    "after:from-color7-light",
    "after:from-color8-light",
    "after:from-color9-light",
    "after:from-color10-light",
    "after:from-color1-dark",
    "after:from-color2-dark",
    "after:from-color3-dark",
    "after:from-color4-dark",
    "after:from-color5-dark",
    "after:from-color6-dark",
    "after:from-color7-dark",
    "after:from-color8-dark",
    "after:from-color9-dark",
    "after:from-color10-dark",
]

export const fadeTransitionTimerSelector = [
    "duration-1500",
    "duration-2500",
]

export const fadeTransitionDelaySelector = [
    "delay-750",
    "delay-1000",
    "delay-1250",
    "delay-1750",
    "delay-1000",
    "delay-2000",
    "delay-3000",
    "delay-4000",
]
